# Wixo 主题配置

# 菜单
menu:
  首页: /wiki
  归档: /wiki/archives
  分类: /wiki/categories
  标签: /wiki/tags
  关于: /about

# 侧边栏组件
widgets:
  - category
  - tag
  - recent_posts
  - archive

# 摘要链接文字
excerpt_link: 阅读全文...

# 社交链接
social:
  GitHub: https://github.com/pistachioss